ros-env:
  ubuntu:
    - ros-melodic-ros-env
ros-watchdog:
  ubuntu:
    - ros-melodic-ros-watchdog
roscore-daemon:
  ubuntu:
    - ros-melodic-roscore-daemon
libaria:
  ubuntu:
    - ros-melodic-libaria
agv:
  ubuntu:
    - ros-melodic-ros-omron-agv
