libaria:
  ubuntu:
    - ros-noetic-libaria
ros_noetic-armer-msgs:
  ubuntu:
    - ros_noetic-armer-msgs
armer_msgs:
  ubuntu:
    - ros-noetic-armer-msgs
roboticstoolbox-python:
  ubuntu:
    pip:
      packages: [roboticstoolbox-python]
