libaria:
  ubuntu:
    - ros-noetic-libaria
armer_msgs:
  ubuntu:
    - ros-noetic-armer-msgs
roboticstoolbox-python:
  ubuntu:
    pip:
      packages:
        - git+https://github.com/petercorke/robotics-toolbox-python.git@future#egg=roboticstoolbox-python
ros_env:
  ubuntu:
    - ros-noetic-ros-env
ros_omron_agv_daemon:
  ubuntu:
    - ros-noetic-ros-omron-agv-daemon
ros_watchdog:
  ubuntu:
    - ros-noetic-ros-watchdog
roscore_daemon:
  ubuntu:
    - ros-noetic-roscore-daemon
qcr_env:
  ubuntu:
    - ros-noetic-qcr-env
robot_bringup_daemon:
  ubuntu:
    - ros-noetic-robot-bringup-daemon
ros_daemon:
  ubuntu:
    - ros-noetic-ros-daemon
armer_teleop:
  ubuntu:
    - ros-noetic-armer-teleop
