libaria:
  ubuntu:
    - ros-noetic-libaria
ros_noetic-armer-msgs:
  ubuntu:
    - ros_noetic-armer-msgs
armer_msgs:
  ubuntu:
    - ros-noetic-armer-msgs
roboticstoolbox-python:
  ubuntu:
    pip:
      packages:
        - git+https://github.com/petercorke/robotics-toolbox-python.git@future
ros_env:
  ubuntu:
    - ros-noetic-ros-env
ros_omron_agv_daemon:
  ubuntu:
    - ros-noetic-ros-omron-agv-daemon
ros_watchdog:
  ubuntu:
    - ros-noetic-ros-watchdog
roscore_daemon:
  ubuntu:
    - ros-noetic-roscore-daemon
